# this builds a single container to run Meshblu locally, with Redis and MongoDB.  Any data persistence is written to the container itself.
# sudo docker build github.com/brianehlert/meshblu.git 
# sudo docker images   ( find the image ID )
# sudo docker run -t -p 3000:3000 -p 5683:5683 -p 1883:1883 <image id>    # direct maps localhost ports to container listener ports
# Check Status:  curl http://localhost:3000/status

# latest ubuntu image
FROM ubuntu:latest

MAINTAINER BrianEh

# install dependencies
RUN apt-get update && apt-get install -y \
	build-essential \
	supervisor \
	libzmq-dev \
	curl \
	libavahi-compat-libdnssd-dev

# install Mongo
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list

# Node from NodeSource  (this runs 'apt-get update')
RUN curl -sL https://deb.nodesource.com/setup | sudo bash -

# install node -  from NodeSource automatically installs legacy pointers (Ubuntu package does not)
RUN apt-get install -y nodejs

# make sure that NPM is at the latest
RUN npm -g update npm

# install MongoDB - automatically sets is as a service
RUN apt-get install -y mongodb-org

# install Redis server - automatically sets it as a service
RUN apt-get install -y redis-server

# global install of bcrypt
RUN npm install --unsafe-perm -g bcrypt

# install forever to run the servers as services
RUN npm install -g forever

# directories
RUN mkdir /opt/blu
RUN mkdir /opt/blu/meshblu
RUN mkdir /opt/blu/gateblu-forever
RUN mkdir /opt/blu/log

# copy the meshblu pull to /opt/blu (this should not copy everything)
COPY ./meshblu /opt/blu/meshblu/
# remove test
# remove docker
COPY ./gateblu-forever /opt/blu/gateblu-forever/
# remove test

# install Meshblu
# RUN cd /opt/blu/meshblu && npm install --production --loglevel warn
# RUN cd /opt/blu/gateblu-forever && npm install --production --loglevel warn
COPY ./meshbluConfig.js /opt/blu/meshblu/config.js
COPY ./ubuntu_meshblu.conf /etc/init/meshblu.conf

# open ports
EXPOSE 3000 5683 1883 27017 6379 22

